version: "3"
services:
nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node-app
node-app:
  build:
    context: .
    args:
      - NODE_ENV=production
  environment:
    - NODE_ENV=production
  command: node index.
mongo:
  image: mongo
  environment:
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=12345
  volumes:
    - mongo-db:/data/db